const User = require('../models/User');
const MeterReading = require('../models/MeterReading');
const AnomalyAlert = require('../models/AnomalyAlert');
const Technician = require('../models/Technician');
const Complaint = require('../models/Complaint');

// Helper for AI Statistical Prediction
const calculatePrediction = async (userId, currentSeason) => {
    const pastReadings = await MeterReading.find({ userId }).sort({ readingDate: -1 }).limit(3);
    let avgUsage = 200; // Default if no past data

    if (pastReadings.length > 0) {
        const sum = pastReadings.reduce((acc, curr) => acc + curr.unitsConsumed, 0);
        avgUsage = sum / pastReadings.length;
    }

    const seasonalMultipliers = {
        'Summer': 1.4,
        'Winter': 1.2,
        'Monsoon': 1.0,
        'Spring': 1.0,
        'Autumn': 1.0
    };

    const multiplier = seasonalMultipliers[currentSeason] || 1.0;
    return avgUsage * multiplier;
};

exports.submitReading = async (req, res) => {
    try {
        const { readingDate, unitsConsumed, season } = req.body;
        const userId = req.user._id;

        // Predict usage to detect anomaly
        const predictedUsage = await calculatePrediction(userId, season);
        const isAnomaly = unitsConsumed > (predictedUsage * 1.5); // 50% more than predicted

        // Calculate bill ($0.15 per unit + $10 base fee)
        const billAmount = (unitsConsumed * 0.15) + 10;

        const reading = new MeterReading({
            userId,
            readingDate,
            unitsConsumed,
            season,
            isAnomaly,
            billAmount
        });
        await reading.save();

        if (isAnomaly) {
            // Create Anomaly Alert
            const alert = new AnomalyAlert({
                userId,
                readingId: reading._id,
                details: `High electricity consumption detected. Actual: ${unitsConsumed}, Predicted: ${predictedUsage.toFixed(2)}`
            });
            await alert.save();

            // Auto Technician Allocation
            const user = await User.findById(userId);
            let tech = await Technician.findOne({ area: user.area, available: true });
            
            // Fallback if no available technician in area
            if (!tech) tech = await Technician.findOne({ available: true });

            let complaintStatus = 'Pending';
            let technicianId = null;

            if (tech) {
                complaintStatus = 'Assigned';
                technicianId = tech._id;
                tech.available = false;
                await tech.save();
            }

            const complaint = new Complaint({
                userId,
                technicianId,
                issueType: 'High Usage Anomaly',
                description: 'Automatically generated complaint due to abnormal electricity usage.',
                status: complaintStatus,
                isAutoGenerated: true
            });
            await complaint.save();
        }

        res.status(201).json({ message: 'Reading submitted successfully', isAnomaly, predictedUsage });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.getDashboardData = async (req, res) => {
    try {
        const userId = req.user._id;
        const readings = await MeterReading.find({ userId }).sort({ readingDate: 1 });
        const alerts = await AnomalyAlert.find({ userId }).populate('readingId').sort({ alertDate: -1 });
        const complaints = await Complaint.find({ userId }).populate('technicianId').sort({ date: -1 });

        // Generate predictions for next month (just for UI graph)
        const nextPrediction = await calculatePrediction(userId, 'Summer'); // default assumption

        res.json({ readings, alerts, complaints, nextPrediction });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.getPrediction = async (req, res) => {
    try {
        const userId = req.user._id;
        const { season } = req.query;
        const prediction = await calculatePrediction(userId, season || 'Summer');
        res.json({ prediction });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.payBill = async (req, res) => {
    try {
        const userId = req.user._id;
        await MeterReading.updateMany({ userId, isPaid: false }, { $set: { isPaid: true } });
        res.json({ message: 'Payment successful' });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};
