const User = require('../models/User');
const MeterReading = require('../models/MeterReading');
const AnomalyAlert = require('../models/AnomalyAlert');
const Technician = require('../models/Technician');
const Complaint = require('../models/Complaint');
const Payment = require('../models/Payment');
const UsageNote = require('../models/UsageNote');


// Helper for AI Statistical Prediction
const calculatePrediction = async (userId, currentSeason) => {
    // Only use healthy (non-anomaly) readings for the baseline
    const pastReadings = await MeterReading.find({ userId, isAnomaly: false })
        .sort({ createdAt: -1 })
        .limit(10);
    
    let avgUsage = 200; // Default fallback

    if (pastReadings.length > 0) {
        const sum = pastReadings.reduce((acc, curr) => acc + curr.unitsConsumed, 0);
        avgUsage = sum / pastReadings.length;
    }

    const seasonalMultipliers = {
        'Summer': 1.4,
        'Winter': 1.2,
        'Monsoon': 1.0,
        'Spring': 1.0,
        'Autumn': 1.0
    };

    const multiplier = seasonalMultipliers[currentSeason] || 1.0;
    return avgUsage * multiplier;
};

exports.submitReading = async (req, res) => {
    try {
        const { readingDate, unitsConsumed, season } = req.body;
        const userId = req.user._id;

        // Predict usage to detect anomaly
        const predictedUsage = await calculatePrediction(userId, season);
        const isHighUsage = unitsConsumed > (predictedUsage * 1.5); 
        const isLowUsage = unitsConsumed < (predictedUsage * 0.4);  
        const isAnomaly = isHighUsage || isLowUsage;

        // Check if this anomaly was expected by the user
        let isExpected = false;
        let surgeReason = "";
        
        if (isHighUsage) {
            const activeNote = await UsageNote.findOne({
                userId,
                startDate: { $lte: new Date(readingDate) },
                endDate: { $gte: new Date(readingDate) },
                isActive: true
            });
            if (activeNote) {
                isExpected = true;
                surgeReason = activeNote.reason;
            }
        }

        console.log(`[Anomaly Detection] User: ${userId}, Units: ${unitsConsumed}, Predicted: ${predictedUsage.toFixed(2)}`);
        console.log(`[Thresholds] High: ${(predictedUsage * 1.5).toFixed(2)}, Low: ${(predictedUsage * 0.4).toFixed(2)}`);
        console.log(`[Result] Anomaly: ${isAnomaly}, Type: ${isHighUsage ? 'High' : (isLowUsage ? 'Low' : 'None')}`);

        // Calculate bill ($0.15 per unit + $10 base fee)
        const billAmount = (unitsConsumed * 0.15) + 10;

        const reading = new MeterReading({
            userId,
            readingDate,
            unitsConsumed,
            season,
            isAnomaly,
            isExpected,
            surgeReason,
            billAmount
        });
        await reading.save();

        if (isAnomaly && !isExpected) {
            const anomalyType = isHighUsage ? 'High Usage' : 'Very low usage';
            const anomalyDetail = isHighUsage 
                ? `High electricity consumption detected. Actual: ${unitsConsumed}, Predicted: ${predictedUsage.toFixed(2)}`
                : `Very low usage detected. Suspected illegal bypass/theft. Actual: ${unitsConsumed}, Predicted: ${predictedUsage.toFixed(2)}`;

            // Create Anomaly Alert
            const alert = new AnomalyAlert({
                userId,
                readingId: reading._id,
                details: anomalyDetail
            });
            await alert.save();

            // Auto Technician Allocation
            const user = await User.findById(userId);
            let tech = await Technician.findOne({ area: user.area });
            
            // Fallback if no technician in area
            if (!tech) tech = await Technician.findOne();

            let complaintStatus = 'Pending';
            let technicianId = null;

            if (tech) {
                complaintStatus = 'Assigned';
                technicianId = tech._id;
                await tech.save();
            }

            const complaint = new Complaint({
                userId,
                technicianId,
                issueType: isLowUsage ? 'Low Usage Anomaly' : 'High Usage Anomaly',
                description: isLowUsage 
                    ? 'Automatically generated investigation task due to suspiciously low usage (potential theft).' 
                    : 'Automatically generated complaint due to abnormal electricity usage.',
                status: complaintStatus,
                isAutoGenerated: true
            });
            await complaint.save();
        }

        res.status(201).json({ message: 'Reading submitted successfully', isAnomaly, predictedUsage });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.getDashboardData = async (req, res) => {
    try {
        const userId = req.user._id;
        const readings = await MeterReading.find({ userId }).sort({ readingDate: 1 });
        const alerts = await AnomalyAlert.find({ userId }).populate('readingId').sort({ alertDate: -1 });
        const complaints = await Complaint.find({ userId }).populate('technicianId').sort({ date: -1 });
        const payments = await Payment.find({ userId }).sort({ paymentDate: -1 });

        // Generate predictions for next month (just for UI graph)
        const nextPrediction = await calculatePrediction(userId, 'Summer');

        // Neighborhood Analytics
        const user = await User.findById(userId);
        const areaUsers = await User.find({ area: user.area });
        const areaUserIds = areaUsers.map(u => u._id);
        
        const areaReadings = await MeterReading.find({ 
            userId: { $in: areaUserIds },
            isAnomaly: false 
        });

        let areaAvg = 0;
        if (areaReadings.length > 0) {
            areaAvg = areaReadings.reduce((acc, curr) => acc + curr.unitsConsumed, 0) / areaReadings.length;
        }

        const latestReading = readings.filter(r => !r.isAnomaly).pop();
        let areaComparison = 0;
        if (areaAvg > 0 && latestReading) {
            areaComparison = ((latestReading.unitsConsumed - areaAvg) / areaAvg) * 100;
        }

        res.json({ readings, alerts, complaints, payments, nextPrediction, areaComparison: Math.round(areaComparison) });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.getPrediction = async (req, res) => {
    try {
        const userId = req.user._id;
        const { season } = req.query;
        const prediction = await calculatePrediction(userId, season || 'Summer');
        res.json({ prediction });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.payBill = async (req, res) => {
    try {
        const userId = req.user._id;
        const unpaidReadings = await MeterReading.find({ userId, isPaid: false });
        
        if (unpaidReadings.length === 0) {
            return res.status(400).json({ message: 'No pending bills found' });
        }

        const totalAmount = unpaidReadings.reduce((sum, r) => sum + r.billAmount, 0);
        const transactionId = 'TXN-' + Math.random().toString(36).substr(2, 9).toUpperCase();

        const payment = new Payment({
            userId,
            amount: totalAmount,
            transactionId,
            readingsPaid: unpaidReadings.map(r => r._id)
        });

        await payment.save();
        await MeterReading.updateMany({ userId, isPaid: false }, { $set: { isPaid: true } });

        res.json({ message: 'Payment successful', transactionId, amount: totalAmount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.submitComplaint = async (req, res) => {
    try {
        const userId = req.user._id;
        const { issueType, description } = req.body;

        const complaint = new Complaint({
            userId,
            issueType,
            description,
            status: 'Pending',
            isAutoGenerated: false
        });
        await complaint.save();

        res.status(201).json({ message: 'Complaint submitted successfully', complaint });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.submitUsageNote = async (req, res) => {
    try {
        const userId = req.user._id;
        const { startDate, endDate, reason, description } = req.body;

        const note = new UsageNote({
            userId,
            startDate,
            endDate,
            reason,
            description
        });

        await note.save();
        res.status(201).json({ message: 'Usage note saved. System will acknowledge this surge.', note });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.getUsageNotes = async (req, res) => {
    try {
        const userId = req.user._id;
        const notes = await UsageNote.find({ userId }).sort({ startDate: -1 });
        res.json(notes);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};
