const mongoose = require('mongoose');

const complaintSchema = new mongoose.Schema({
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    technicianId: { type: mongoose.Schema.Types.ObjectId, ref: 'Technician' },
    issueType: { type: String, required: true },
    description: { type: String, required: true },
    status: { type: String, enum: ['Pending', 'Assigned', 'Resolved'], default: 'Pending' },
    date: { type: Date, default: Date.now },
    isAutoGenerated: { type: Boolean, default: false }
}, { timestamps: true });

module.exports = mongoose.model('Complaint', complaintSchema);
